src/ocean_nutrition/visualisations/__init__.py
from ocean_nutrition.visualisations.views import views

def register_app(app):
    app.register_blueprint(views)
    pass

src/ocean_nutrition/visualisations/views.py
from flask import Blueprint
from flask import render_template

views = Blueprint('views', __name__,
	static_folder='static', 
	static_url_path='', 
	template_folder='templates')

@views.route('/')
def index():
    return render_template('index.html')

@views.route('/search')
def search():
    return render_template('search.html')

@views.route('/diary')
def diary():
    return render_template('diary.html')

src/ocean_nutrition/visualisations/templates/_layout.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <title>OCEAN Nutrition</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}{% endblock %}
</head>
<body>
	{% block body %}{% endblock %}
	
	{% block js %}{% endblock %}
</body>

src/ocean_nutrition/visualisations/templates/diary.html
{% extends "_layout.html" %}
<!-- START body-->
{% block body %}
<h1 class="title">Diary</h1>
<h3 class="subtitle">OCEAN Nutrition</h3>

<p class="nav">
    <a href="{{ url_for('views.index') }}">Home</a>
    | <a href="{{ url_for('views.diary') }}">Diary</a>
    | <a href="{{ url_for('views.search') }}">Search</a>
    | <a href="{{ url_for('views.index') }}">Profile</a>
</p>

<h3>Current Metabolic Rate: <span id="result">...</span></h3>

<form method="POST" action="#" style="display: none;">
  <label for="fname">Calorie Density (kcal/100g):</label>
  <input type="text" id="fname" name="fname"><br><br>
  <label for="lname">Weight (g):</label>
  <input type="text" id="lname" name="lname"><br><br>
  <input type="submit" value="Submit">
</form>

{% endblock %}
<!-- END body-->

<!-- START css -->
{% block css %}
<style>

.title, .subtitle, .nav {
    margin: 0;
    padding: 0;
    text-align: center;
    margin-bottom: 10px;

    .a {
    	padding-right: 10px;
    	padding-left: 10px;
    }
}

</style>
{% endblock %}
<!-- END css -->

<!-- START js -->
{% block js %}
<script>
(function get_average_calorie_density(){
    const url = `/tracker`;
    fetch(url)
    .then((resp) => resp.json())
    .then(function(data) {
        document.getElementById('result').innerHTML = data['average_calorie_density']
    })
    .catch(function(error){
        alert(error)
    })

})();
</script>
{% endblock %}
<!-- END js -->

src/ocean_nutrition/visualisations/templates/index.html
{% extends "_layout.html" %}
<!-- START body-->
{% block body %}
<h1 class="title">Home</h1>
<h3 class="subtitle">OCEAN Nutrition</h3>

<p class="nav">
    <a href="{{ url_for('views.index') }}">Home</a>
    | <a href="{{ url_for('views.diary') }}">Diary</a>
    | <a href="{{ url_for('views.search') }}">Search</a>
    | <a href="{{ url_for('views.index') }}">Profile</a>
</p>
{% endblock %}
<!-- END body-->

<!-- START css -->
{% block css %}
<style>

h1, h2, h3, h4, h5, h6 {
	margin: 0;
	padding: 0;
}

.title, .subtitle, .nav {
    text-align: center;
    margin-bottom: 10px;

    .a {
    	padding-right: 10px;
    	padding-left: 10px;
    }
}

</style>
{% endblock %}
<!-- END css -->

<!-- START js -->
{% block js %}

{% endblock %}
<!-- END js -->

src/ocean_nutrition/visualisations/templates/profile.html
{% extends "_layout.html" %}
<!-- START body-->
{% block body %}
<h1 class="title">Profile</h1>
<h3 class="subtitle">OCEAN Nutrition</h3>

<p class="nav">
	<a href="{{ url_for('views.index') }}">Home</a>
	| <a href="{{ url_for('views.index') }}">Diary</a>
    | <a href="{{ url_for('views.search') }}">Search</a>
	| <a href="{{ url_for('views.index') }}">Profile</a>
</p>
{% endblock %}
<!-- END body-->

<!-- START css -->
{% block css %}
<style>

h1, h2, h3, h4, h5, h6 {
	margin: 0;
	padding: 0;
}

.title, .subtitle, .nav {
    text-align: center;
    margin-bottom: 10px;

    .a {
    	padding-right: 10px;
    	padding-left: 10px;
    }
}

</style>
{% endblock %}
<!-- END css -->

<!-- START js -->
{% block js %}

{% endblock %}
<!-- END js -->

src/ocean_nutrition/visualisations/templates/search.html
{% extends "_layout.html" %}
<!-- START body-->
{% block body %}
<h1 class="title">Search</h1>
<h3 class="subtitle">OCEAN Nutrition</h3>

<p class="nav">
    <a href="{{ url_for('views.index') }}">Home</a>
    | <a href="{{ url_for('views.diary') }}">Diary</a>
    | <a href="{{ url_for('views.search') }}">Search</a>
    | <a href="{{ url_for('views.index') }}">Profile</a>
</p>

<section id="x-foo-from-template">

  <div class="wrapper">
    <div>
      <a class="button" id="startButton" style="text-decoration: underline;">Start</a>
      <a class="button" id="resetButton" style="text-decoration: underline;">Stop</a>
    </div>

    <div>
      <video id="video" width="100%" height="400" style="border: 1px solid gray;"></video>
    </div>

    <div id="sourceSelectPanel" style="display: none;">
      <label for="sourceSelect">Change video source:</label>
      <select id="sourceSelect" style="max-width: 400px;"> </select>
    </div>

    <label>Result:</label>
    <pre><code id="result"></code></pre>

    <iframe  id="data" src="/search/0" width="100%" ></iframe> 

  </div>
</section>



{% endblock %}
<!-- END body-->

<!-- START css -->
{% block css %}
<style>

h1, h2, h3, h4, h5, h6, p {
    margin: 0;
    padding: 0;
}

.title, .subtitle, .nav {
    text-align: center;
    margin-bottom: 10px;

    .a {
        padding-right: 10px;
        padding-left: 10px;
    }
}

</style>
{% endblock %}
<!-- END css -->

<!-- START js -->
{% block js %}
<script type="text/javascript" src="https://unpkg.com/@zxing/library@latest"></script>
<script type="text/javascript">
function search_product(barcode){
    const url = `http://localhost:5000/search/${barcode}`;
    // fetch(url)
    // .then((resp) => resp.json())
    // .then(function(data) {
    //     document.getElementById('result').innerHTML = 
    //         `<p>---
    //         <br  />Barcode: <span>${data['barcode']}</span></p>`;
    // })
    // .catch(function(error){
    //     alert(error)
    // })
    document.getElementById('data').src = url;

};
</script>
<script type="text/javascript">
  window.addEventListener('load', function () {
            let selectedDeviceId;
            const codeReader = new ZXing.BrowserBarcodeReader()
            console.log('ZXing code reader initialized')
            codeReader.getVideoInputDevices()
                .then((videoInputDevices) => {
                    const sourceSelect = document.getElementById('sourceSelect')
                    selectedDeviceId = videoInputDevices[0].deviceId
                    if (videoInputDevices.length > 1) {
                        videoInputDevices.forEach((element) => {
                            const sourceOption = document.createElement('option')
                            sourceOption.text = element.label
                            sourceOption.value = element.deviceId
                            sourceSelect.appendChild(sourceOption)
                        })

                        sourceSelect.onchange = () => {
                            selectedDeviceId = sourceSelect.value;
                        }

                        const sourceSelectPanel = document.getElementById('sourceSelectPanel')
                        sourceSelectPanel.style.display = 'block'
                    }

                    document.getElementById('startButton').addEventListener('click', () => {
                        codeReader.decodeOnceFromVideoDevice(selectedDeviceId, 'video').then((result) => {
                            console.log(result)
                            search_product(result.text)
                        }).catch((err) => {
                            console.error(err)
                            document.getElementById('result').textContent = err
                        })
                        console.log(`Started continous decode from camera with id ${selectedDeviceId}`)
                    })

                    document.getElementById('resetButton').addEventListener('click', () => {
                        document.getElementById('result').textContent = '';
                        codeReader.reset();
                        console.log('Reset.')
                    })

                })
                .catch((err) => {
                    console.error(err)
                })
        })
</script>

{% endblock %}
<!-- END js -->